
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from function_interface import *


ASSETS_PATH = Path(r"./assets/frame0")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1095x636")
window.configure(bg = "#000000")


variableGlobale()


canvas = Canvas(
    window,
    bg = "#000000",
    height = 636,
    width = 1095,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_image_1_select = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: change_color_button(button_1,button_image_1,button_image_1_select),
    relief="flat",
    text=False
)
button_1.place(
    x=645.0,
    y=409.0,
    width=188.0,
    height=33.0
)


button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_image_2_select = PhotoImage(
    file=relative_to_assets("button_10.png"))

button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: change_color_button(button_2,button_image_2,button_image_2_select),
    relief="flat",
    text=False
)
button_2.place(
    x=645.0,
    y=350.0,
    width=188.0,
    height=33.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_image_3_select = PhotoImage(
    file=relative_to_assets("button_11.png"))

button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: change_color_button(button_3,button_image_3,button_image_3_select),
    relief="flat",
    text=False
)
button_3.place(
    x=645.0,
    y=291.0,
    width=188.0,
    height=33.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_image_4_select = PhotoImage(
    file=relative_to_assets("button_12.png"))

button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: change_color_button(button_4,button_image_4,button_image_4_select),
    relief="flat",
    text=False
)
button_4.place(
    x=645.0,
    y=232.0,
    width=188.0,
    height=33.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_image_5_select = PhotoImage(
    file=relative_to_assets("button_13.png"))

button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: change_color_button(button_5,button_image_5,button_image_5_select),
    relief="flat",
    text=False
)
button_5.place(
    x=297.0,
    y=409.0,
    width=188.0,
    height=33.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_image_6_select = PhotoImage(
    file=relative_to_assets("button_14.png"))

button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: change_color_button(button_6,button_image_6,button_image_6_select),
    relief="flat",
    text=False
)
button_6.place(
    x=297.0,
    y=350.0,
    width=188.0,
    height=33.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_image_7_select = PhotoImage(
    file=relative_to_assets("button_15.png"))

button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: change_color_button(button_7,button_image_7,button_image_7_select),
    relief="flat",
    text=False
)
button_7.place(
    x=297.0,
    y=291.0,
    width=188.0,
    height=33.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_image_8_select = PhotoImage(
    file=relative_to_assets("button_16.png"))

button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: change_color_button(button_8,button_image_8,button_image_8_select),
    relief="flat",
    text=False
)
button_8.place(
    x=297.0,
    y=232.0,
    width=188.0,
    height=33.0
)

canvas.create_text(
    642.0,
    174.0,
    anchor="nw",
    text="Choisir 1 à 4 prédicteur",
    fill="#38B6FF",
    font=("Junge Regular", 18 * -1)
)

canvas.create_text(
    306.0,
    174.0,
    anchor="nw",
    text="Choisir 1 à 4 sources",
    fill="#38B6FF",
    font=("Junge Regular", 18 * -1)
)

canvas.create_text(
    197.0,
    33.0,
    anchor="nw",
    text="WHO IS THE BEST PREDICTOR ?",
    fill="#38B6FF",
    font=("JuliusSansOne Regular", 36 * -1)
)

canvas.create_rectangle(
    159.99932861328125,
    107.5,
    924.9993896484375,
    108.5,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()